module.exports = {
  /* API endpoints for widgets that need to fetch external data */
  widgetApiEndpoints: {
    anonAddy: "https://app.anonaddy.com",
    astronomyPictureOfTheDay: "https://apod.as93.net/apod",
    blacklistCheck: "https://api.blacklistchecker.com/check",
    codeStats: "https://codestats.net/",
    covidStats: "https://disease.sh/v3/covid-19",
    cryptoPrices: "https://api.coingecko.com/api/v3/coins/",
    cryptoWatchList: "https://api.coingecko.com/api/v3/coins/markets/",
    cveVulnerabilities: "https://www.cvedetails.com/json-feed.php",
    domainMonitor: "https://api.whoapi.com",
    ethGasPrices: "https://ethgas.watch/api/gas",
    ethGasHistory: "https://ethgas.watch/api/gas/trend",
    exchangeRates: "https://v6.exchangerate-api.com/v6/",
    flights: "https://aerodatabox.p.rapidapi.com/flights/airports/icao/",
    githubTrending: "https://gh-trending-repos.herokuapp.com/",
    hackernewsTrending: "https://hacker-news.firebaseio.com/v0",
    healthChecks: "https://healthchecks.io/api/v1/checks",
    holidays:
      "https://kayaposoft.com/enrico/json/v2.0/?action=getHolidaysForDateRange",
    jokes: "https://v2.jokeapi.dev/joke/",
    news: "https://api.currentsapi.services/v1/latest-news",
    mullvad: "https://am.i.mullvad.net/json",
    mvg: "https://www.mvg.de/api/fib/v2/",
    publicIp: "https://ipapi.co/json",
    publicIp2: "https://api.ipgeolocation.io/ipgeo",
    publicIp3: "http://ip-api.com/json",
    readMeStats: "https://github-readme-stats.vercel.app/api",
    rescueTime: "https://www.rescuetime.com/anapi/data",
    rssToJson: "https://api.rss2json.com/v1/api.json",
    sportsScores: "https://www.thesportsdb.com/api/v1/json",
    stockPriceChart: "https://www.alphavantage.co/query",
    tflStatus:
      "https://api.tfl.gov.uk/line/mode/dlr,elizabeth-line,overground,tram,tube/status",
    walletBalance: "https://api.blockcypher.com/v1",
    walletQrCode: "https://www.bitcoinqrcodemaker.com/api",
    weather: "https://api.openweathermap.org/data/2.5/weather",
    weatherForecast: "https://api.openweathermap.org/data/3.0/onecall?lat=33.4936&lon=-111.9167&units=imperial&appid=f79df586960e6ddbb36be5b6b2d57b5d",
    xkcdComic: "https://xkcd.vercel.app/",
  },
};
