export const iconMappings = {
    "01d": "wi-day-sunny",
    "01n": "wi-night-clear",
    "02d": "wi-day-cloudy-high",
    "02n": "wi-night-alt-cloudy",
    "03d": "wi-day-cloudy-high",
    "03n": "wi-night-alt-cloudy",
    "04d": "wi-day-cloudy-high",
    "04n": "wi-night-alt-cloudy",
    "09d": "wi-day-showers",
    "09n": "wi-night-alt-showers",
    "10d": "wi-day-rain-mix",
    "10n": "wi-night-alt-rain-mix",
    "11d": "wi-day-thunderstorm",
    "11n": "wi-night-thunderstorm",
    "13d": "wi-day-snow",
    "13n": "wi-night-snow",
    "50d": "wi-day-haze",
    "50n": "wi-night-haze",
    default: "wi-meteor",
};